" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

source ~/.vim_my/basic.vim
source ~/.vim_my/plugins.vim
source ~/.vim_my/key.vim

"set runtimepath+=~/.vim_runtime
"source ~/.vim_runtime/vimrcs/basic.vim
"source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
"source ~/.vim_runtime/vimrcs/extended.vim
"try
"  source ~/.vim_runtime/my_configs.vim
"catch
"endtry
